/// `_headers` — the browser-caching policy for everything that is not a page.
///
/// Cloudflare Pages reads this file from the root of the upload, applies it to
/// matching responses, and does not serve the file itself.
///
/// ## What it is for
///
/// Pages' default on every response is `public, max-age=0, must-revalidate`
/// (measured on the dev deployment, 2026-08-15). The bytes land in the
/// browser's cache, but the browser must ask the edge "still valid?" before
/// reusing them — a conditional request, a `304`, and a full round trip. Every
/// link on this site is a whole new document, so **each page view pays that
/// round trip for the stylesheet, the script, the emblem and every WOFF2 face
/// it uses** (8 faces, 328 KB, 2–4 per page), none of which changed between one
/// sutta and the next. On the slow connections this surface exists for, that is
/// the difference between a page that renders and a page that waits.
///
/// The HTML keeps the default and must: a page's URL is stable while its
/// content is not, so a reader who returns to a sutta has to get the current
/// one.
///
/// ## One tier, because every URL here carries a hash
///
/// A year of `immutable` is only safe when a new file arrives under a new URL,
/// and [SiteAssets] makes that true of all five — the stylesheet, the script,
/// the search index, the emblem, and the font faces through the `@font-face`
/// rules in the stylesheet. None of them can go stale: a changed file is a
/// changed URL, and an unchanged one is not worth revalidating.
///
/// This used to be two tiers. The emblem and the fonts had no version, so they
/// got a week of `max-age` — long enough to skip revalidating across one
/// sitting, short enough to bound the wait for a corrected font face. Hashing
/// them retired the compromise and, with it, the second tier and the three
/// exact-path rules that kept the two apart.
///
/// ## Rules must not overlap
///
/// > An incoming request which matches multiple rules' URL patterns will
/// > inherit all rules' headers.
///
/// — and where two matched rules set the *same* header, Pages joins the values
/// with a comma. A `/assets/*` blanket beside a `/assets/emblem.png` exception
/// would therefore not override anything; it would emit
/// `Cache-Control: public, max-age=31536000, immutable, public, max-age=604800`
/// and leave the real policy to whatever the browser makes of that. The two
/// patterns below are disjoint, which is the only reason the file is this
/// short. A future rule setting a *different* header (`Content-Security-Policy`
/// on `/*`, say) can safely span both.
library;

import 'site_assets.dart';
import 'web_fonts.dart';

/// Path under the output directory. Root of the upload, not `assets/`.
const String cacheHeadersOutputPath = '_headers';

/// A year, the conventional ceiling. Safe for every path below because each one
/// is versioned by content.
const String _immutable = 'public, max-age=31536000, immutable';

/// Built from the same constants the rest of the build writes and links, so a
/// renamed asset cannot leave a rule pointing at a path nothing is served from.
///
/// Two wildcards rather than five exact paths. Exact paths were the safer shape
/// while `assets/` held a mix of versioned and unversioned files and a wildcard
/// could not tell them apart; now that everything under both directories is
/// versioned, naming them one by one would only be five chances to forget the
/// sixth.
String buildCacheHeaders() {
  const rules = <String, String>{
    '/$assetsOutputDir/*': _immutable,
    '/$fontsOutputDir/*': _immutable,
  };

  final out = StringBuffer();
  out.writeln('# GENERATED by wisdom-ssg — see lib/render/cache_headers.dart.');
  out.writeln('# Pages consumes this file; it is never served.');
  out.writeln('# Everything matched below carries a ?v=<hash of its bytes>,');
  out.writeln('# so a changed file is a changed URL — see site_assets.dart.');
  out.writeln('# HTML is deliberately absent: it keeps Pages\' default');
  out.writeln(
      '# `max-age=0, must-revalidate`, because a page\'s URL is stable');
  out.writeln('# while its content is not.');
  for (final rule in rules.entries) {
    out.writeln();
    out.writeln(rule.key);
    out.writeln('  Cache-Control: ${rule.value}');
  }
  return out.toString();
}
