/// The four reading layouts — the one definition the markup and the stylesheet
/// both build from.
///
/// Mirrors: lib/presentation/models/reader_layout.dart
///
/// These lived in two files until a review caught it: `page_template.dart` held
/// the list, `stylesheet.dart` held a parallel list of ids *and* spelled each id
/// out again across a dozen rules. Nothing tied the two together, and the way
/// that fails is silent — rename an id and every selector stops matching, the
/// whole layout engine dies, and neither the analyzer nor a build error says a
/// word, because a CSS rule that matches nothing is not an error. There is no
/// test suite here to catch it either.
///
/// So both sides import this, and the CSS is generated by walking the same list
/// the HTML is.
library;

/// One button of the reading-layout switcher, and the radio behind it.
typedef ReadingLayout = ({
  /// DOM id, referenced by every selector in the layout CSS.
  String id,

  /// The app's `ReaderLayout.name`. Carried as the radio's `value` so P4's
  /// `?layout=` handler — whose token grammar is the enum name, per the locked
  /// shareable-link contract — can check the right radio by matching on it,
  /// rather than needing a second table mapping tokens to ids.
  String token,

  /// Accessible name. Sighted readers get [glyph]; this is what is announced.
  String label,

  /// What the button shows: a letter, or an inline SVG.
  String glyph,
});

/// The four ids, each written exactly once in the codebase.
///
/// Named individually because the stylesheet does not treat them uniformly —
/// hiding `.si` is a different rule from splitting the grid — so it needs to
/// name one layout at a time, and a bare `'L-si'` typed into a selector is the
/// silent-failure mode this library exists to remove.
const String paliOnlyLayoutId = 'L-pali';
const String sinhalaOnlyLayoutId = 'L-si';
const String sideBySideLayoutId = 'L-sbs';
const String stackedLayoutId = 'L-stack';

/// In the order the app's `ReaderLayout` enum declares them.
///
/// Labels are the app's shipped Sinhala strings from
/// `lib/core/localization/l10n/app_si.arb` — `layoutPaliOnly` and friends — not
/// new wording invented for this surface. The static-site plan's §7 sketch
/// suggested "පාළි / සිංහල / පාළි + සිංහල / තට්ටු"; those were never in the app,
/// and two names for one control is how the two surfaces start to drift.
const List<ReadingLayout> readingLayouts = [
  (
    id: paliOnlyLayoutId,
    token: 'paliOnly',
    label: 'පාළි පමණයි',
    glyph: 'P',
  ),
  (
    id: sinhalaOnlyLayoutId,
    token: 'sinhalaOnly',
    label: 'සිංහල පමණයි',
    glyph: 'S',
  ),
  (
    id: sideBySideLayoutId,
    token: 'sideBySide',
    label: 'දෙකම',
    glyph: '$_iconFrame<line x1="12" y1="4" x2="12" y2="20"/></svg>',
  ),
  (
    id: stackedLayoutId,
    token: 'stacked',
    label: 'ගොඩගැසූ',
    glyph: '$_iconFrame<line x1="3" y1="12" x2="21" y2="12"/></svg>',
  ),
];

/// The layout baked `checked` into every readable page.
///
/// The app has no single default — `resolveSeedLayout` seeds **stacked in
/// portrait, sideBySide in landscape** — and CSS cannot switch a `checked`
/// attribute on orientation. So side-by-side is baked, and its own rule carries
/// the second column only above [narrowFallbackLayoutId]'s breakpoint; below it
/// the page falls back to the base single column, which *is* stacked. One
/// default in the HTML, both of the app's behaviours on screen.
const String defaultLayoutId = sideBySideLayoutId;

/// What [defaultLayoutId] actually renders as on a narrow screen.
///
/// Load-bearing for the toolbar, not just the grid: below the breakpoint the
/// two are the same rendering, so side-by-side is not offered and *this*
/// button is the one that lights. A control that says the page is in a layout
/// it is not in is worse than one option fewer.
const String narrowFallbackLayoutId = stackedLayoutId;

/// The shared opening of both layout icons: a page outline, split by one line.
/// Inline SVG rather than a font or an image — it is ~90 bytes, needs no extra
/// request, and inherits `currentColor` so the checked state needs no second
/// asset.
const String _iconFrame = '<svg class="layout-icon" viewBox="0 0 24 24" '
    'fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true">'
    '<rect x="3" y="4" width="18" height="16" rx="1.5"/>';
