import 'sitemap.dart';

/// Path under the output directory. Crawlers look for exactly `/robots.txt` and
/// nowhere else.
const String robotsOutputPath = 'robots.txt';

/// `robots.txt` — allow everything, and say where the sitemap is.
///
/// ## The `Sitemap:` line is the reason the file exists
///
/// The apex has nothing to hide: every page is public scripture, and there is
/// no admin path, no search endpoint and no faceted URL space to keep a crawler
/// out of. Without this file the site behaves identically — a missing
/// `robots.txt` means "crawl everything". What it adds is the one line that
/// cannot be said any other way: where `sitemap.xml` is. Google Search Console
/// can be told directly, and Bing and the rest cannot.
///
/// ## Allow, never Disallow — including on the previews
///
/// This file is written on every build shape, dev preview included, and it says
/// the same thing on all of them. That is deliberate and it is the same
/// reasoning `static-web-hosting.md` records for the app origin: a preview is
/// kept out of the index by Cloudflare's automatic `X-Robots-Tag: noindex`,
/// which is a header on the *response* — and a crawler that has been told
/// `Disallow` never fetches the response, so it never reads the header. A
/// blocked URL can still be indexed from its inbound links, with no title and
/// no description, which is the outcome `Disallow` is usually reached for to
/// prevent.
///
/// Two rules only. No `Crawl-delay` — Google ignores it, and this is static
/// files on a CDN with nothing to protect from load.
String buildRobots({required String origin}) => '''
# GENERATED by wisdom-ssg — see lib/render/robots.dart.
# Allow-all is the whole policy; the Sitemap line is why this file is here.
User-agent: *
Allow: /

Sitemap: $origin/$sitemapOutputPath
''';
