// GENERATED by `dart run static_site_generator/tool/plan_corpus.dart
// --write-snapshot`. Change the rule
// (`static_site_generator/lib/domain/preamble_planner.dart`) and regenerate
// rather than hand-editing.

/// Every container whose preamble is the book's introduction to the chapter
/// rather than its title — 110 of them, frozen from one full-corpus
/// run of the rule.
///
/// A container's page is normally pure navigation: no layout switcher, no
/// prev/next, and a column sized for link rows. For the containers named here
/// that would serve running text as if it were a menu, so they are **readable**
/// instead — `SitePage.isReadable` is this set unioned with every sutta and
/// chapter page.
///
/// **A superset of the pages it changes, deliberately.** Some of these
/// containers are already whole-vagga chapters, which are readable whatever
/// their preamble holds, so their key does nothing today.
/// `FIGURES.readableContainerTocs` is the count that is actually load-bearing.
/// Naming them anyway is what keeps the two snapshots orthogonal: this one
/// answers "does this container own text", `foldedLeafKeys` answers "which
/// pages exist", and neither has to be correct for the other to be. A grouping
/// change that turns a chapter back into a TOC then finds the answer already
/// here, rather than serving an introduction as a menu until someone notices.
///
/// **An absent key means "not readable".** That is the safe direction here, and
/// it is the opposite of `foldedLeafKeys`: a container that gains an
/// introduction upstream keeps the page it has until someone regenerates, where
/// the opposite default would drop a bare link list into the reading chain that
/// every reader walking prev/next would meet. Neither direction moves a URL —
/// nothing in this file decides which pages *exist*.
///
/// Generated code rather than a bundled asset, for the same reason as
/// `foldedLeafKeys`: one `const` compiles into both surfaces from one place.
/// Written in reading order.
///
/// The count above is the only corpus figure written here, and it is
/// interpolated by the writer rather than typed. Every other one lives in
/// `static_site_generator/CORPUS_FIGURES.md`.
///
/// See `docs/todo/web-strategy/reading-units-and-grouping.md`.
const Set<String> textBearingContainerKeys = {
  'vp-prj-2-2',
  'vp-prj-2-3',
  'vp-prj-2-4',
  'vp-prj-3-1',
  'vp-prj-3-2',
  'vp-prj-3-3',
  'vp-prj-3-4',
  'vp-prj-3-5',
  'vp-pct-1-2',
  'vp-pct-1-3',
  'vp-pct-1-3-1',
  'vp-pct-1-3-2',
  'vp-pct-1-3-3',
  'vp-pct-1-3-4',
  'vp-pct-1-3-5',
  'vp-pct-1-3-6',
  'vp-pct-1-3-7',
  'vp-cv-4-8',
  'vp-pv-9',
  'vp-pv-10',
  'vp-pv-14',
  'vp-pv-15',
  'an-1-8',
  'an-1-9',
  'an-1-10',
  'an-2-2-10',
  'an-2-3-11',
  'an-2-3-12',
  'an-2-3-13',
  'an-2-3-14',
  'an-2-3-15',
  'an-2-16',
  'an-3-1-2',
  'an-3-1-5',
  'kn-thag',
  'kn-mn-2',
  'kn-mn-3',
  'kn-mn-4',
  'kn-mn-5',
  'kn-mn-6',
  'kn-mn-7',
  'kn-mn-8',
  'kn-mn-9',
  'kn-mn-10',
  'kn-mn-11',
  'kn-mn-12',
  'kn-mn-13',
  'kn-mn-14',
  'kn-mn-15',
  'kn-mn-16',
  'kn-nc-17',
  'kn-ps-1-2',
  'kn-nett-3-4',
  'atta-vp-prj-0',
  'atta-vp-prj-1',
  'atta-vp-prj-2-2',
  'atta-vp-prj-2-3',
  'atta-vp-prj-2-4',
  'atta-vp-pct-2-1',
  'atta-vp-cv-4-8',
  'atta-vp-pv-3',
  'atta-mn-1-1-1',
  'atta-mn-1-1-2',
  'atta-mn-1-1-4',
  'atta-mn-1-1-5',
  'atta-mn-1-1-9',
  'atta-mn-1-1-10',
  'atta-mn-1-3-4',
  'atta-mn-3-3-9',
  'atta-an-1-0',
  'atta-an-10-4-2',
  'atta-an-10-5-1',
  'atta-kn-khp-0',
  'atta-kn-iti-0',
  'atta-kn-snp',
  'atta-kn-thag-0',
  'atta-kn-jat-0',
  'atta-kn-jat-22-1',
  'atta-kn-jat-22-4',
  'atta-kn-jat-22-9',
  'atta-kn-ps-1-1-54',
  'atta-kn-ps-1-4-2',
  'atta-kn-ps-1-4-3',
  'atta-kn-ps-1-4-4',
  'atta-kn-ap-0',
  'atta-kn-ap-1-39',
  'atta-kn-bv-28',
  'atta-kn-cp-0',
  'atta-kn-nett',
  'atta-kn-nett-2',
  'atta-kn-nett-3-4',
  'atta-ap-dhs-0',
  'atta-ap-dhs-2-5',
  'atta-ap-dhs-2-6-2',
  'atta-ap-dhs-2-7-2',
  'atta-ap-dhs-3-1',
  'atta-ap-vbh-1-1',
  'atta-ap-vbh-4-1',
  'atta-ap-vbh-17-1',
  'atta-ap-vbh-17-10',
  'atta-ap-dhk',
  'atta-ap-pug',
  'atta-ap-kvu',
  'atta-ap-yam',
  'atta-ap-yam-10',
  'atta-ap-pat',
  'anya-vm-2',
  'anya-vm-3',
  'anya-vm-4',
  'anya-vm-16-5',
};
