// GENERATED by `dart run static_site_generator/tool/plan_corpus.dart
// --write-alignment`. Change the rule
// (`static_site_generator/lib/domain/coordinate_planner.dart`) and regenerate
// rather than hand-editing.

/// Leaves whose `tree.json` coordinate points at the wrong row, and the row it
/// should point at — 88 of them, frozen from one full-corpus
/// run of the rule.
///
/// ## What is wrong upstream
///
/// A node's coordinate is the `[pageIndex, entryIndexInPage]` where its text
/// **begins**, and every slice in the corpus is cut from one coordinate to the
/// next. For the leaves named here upstream put the coordinate on the label
/// that *closes* the unit instead — BJT prints those section names as a
/// colophon, after the text they name — so the slice opens on one unit's name
/// and runs through the *next* unit's body. The page then carries the right
/// title over the wrong text, and its `#fragment` lands one unit early: a page
/// that is wrong without looking wrong, which is why it survived every count,
/// link check and byte-diff the build does.
///
/// `SliceAlignment` is the detector; this is the correction. They are kept
/// apart on purpose — the detector is asked of whatever tree is loaded, so
/// running it *after* this map is applied is what proves the correction still
/// covers the defect rather than merely having covered it once.
///
/// ## Why a map and not an edit
///
/// `assets/data/tree.json` is vendored from tipitaka.lk with no provenance, and
/// the next re-sync overwrites it. A hand-edit there is a fix that silently
/// disappears; a `const` here is code, survives the re-sync, and its git diff
/// is the review — one line per leaf whose text moves. It also reaches both
/// surfaces from one place, which a per-app patch could not.
///
/// **It moves text, not URLs.** Nothing here changes which pages exist or what
/// they are called. Both other snapshots are *measured* from the corrected tree
/// and so must be regenerated after this file changes — a container whose
/// preamble was holding a swallowed body stops being an introduction once the
/// body goes back to the leaf that owns it.
///
/// **The defect is upstream's and the correction should be too.** This map is
/// the local answer while the report is open; if tipitaka.lk fixes the
/// coordinates, regenerating writes an empty map and nothing else changes.
///
/// The count above is the only corpus figure written here, and it is
/// interpolated by the writer rather than typed. Every other one lives in
/// `static_site_generator/CORPUS_FIGURES.md`.
///
/// See `docs/todo/web-strategy/reading-units-and-grouping.md` — B5.
const Map<String, ({int page, int entry})> correctedTreeCoordinates = {
  // was (page: 50, entry: 7), now opens on "4. 7."
  'kn-vv-4-7': (page: 50, entry: 8),
  // was (page: 25, entry: 8), now opens on "2. 9."
  'kn-pv-2-9': (page: 25, entry: 9),
  // was (page: 42, entry: 4), now opens on "3. 4."
  'kn-pv-3-4': (page: 42, entry: 5),
  // was (page: 65, entry: 9), now opens on "4. 3."
  'kn-pv-4-3': (page: 66, entry: 0),
  // was (page: 41, entry: 2), now opens on "2."
  'ap-vbh-18-2': (page: 42, entry: 6),
  // was (page: 42, entry: 7), now opens on "3."
  'ap-vbh-18-3': (page: 46, entry: 4),
  // was (page: 46, entry: 5), now opens on "4."
  'ap-vbh-18-4': (page: 48, entry: 10),
  // was (page: 48, entry: 11), now opens on "5."
  'ap-vbh-18-5': (page: 54, entry: 10),
  // was (page: 54, entry: 11), now opens on "6."
  'ap-vbh-18-6': (page: 55, entry: 7),
  // was (page: 55, entry: 8), now opens on "7."
  'ap-vbh-18-7': (page: 58, entry: 14),
  // was (page: 58, entry: 15), now opens on "8."
  'ap-vbh-18-8': (page: 60, entry: 2),
  // was (page: 60, entry: 3), now opens on "9."
  'ap-vbh-18-9': (page: 61, entry: 5),
  // was (page: 61, entry: 6), now opens on "10."
  'ap-vbh-18-10': (page: 62, entry: 0),
  // was (page: 12, entry: 10), now opens on "8. 1. 1."
  'vp-pct-1-3-1-1': (page: 12, entry: 4),
  // was (page: 13, entry: 5), now opens on "8. 1. 2."
  'vp-pct-1-3-1-2': (page: 13, entry: 0),
  // was (page: 13, entry: 11), now opens on "8. 1. 3."
  'vp-pct-1-3-1-3': (page: 13, entry: 6),
  // was (page: 13, entry: 17), now opens on "8. 1. 4."
  'vp-pct-1-3-1-4': (page: 13, entry: 12),
  // was (page: 14, entry: 5), now opens on "8. 1. 5."
  'vp-pct-1-3-1-5': (page: 14, entry: 0),
  // was (page: 14, entry: 11), now opens on "8. 1. 6."
  'vp-pct-1-3-1-6': (page: 14, entry: 6),
  // was (page: 14, entry: 17), now opens on "8. 1. 7."
  'vp-pct-1-3-1-7': (page: 14, entry: 12),
  // was (page: 15, entry: 5), now opens on "8. 1. 8."
  'vp-pct-1-3-1-8': (page: 15, entry: 0),
  // was (page: 15, entry: 11), now opens on "8. 1. 9."
  'vp-pct-1-3-1-9': (page: 15, entry: 6),
  // was (page: 15, entry: 17), now opens on "8. 1. 10."
  'vp-pct-1-3-1-10': (page: 15, entry: 12),
  // was (page: 16, entry: 6), now opens on "8. 2. 1."
  'vp-pct-1-3-2-1': (page: 16, entry: 1),
  // was (page: 16, entry: 12), now opens on "8. 2. 2."
  'vp-pct-1-3-2-2': (page: 16, entry: 7),
  // was (page: 16, entry: 18), now opens on "8. 2. 3."
  'vp-pct-1-3-2-3': (page: 16, entry: 13),
  // was (page: 17, entry: 5), now opens on "8. 2. 4."
  'vp-pct-1-3-2-4': (page: 17, entry: 0),
  // was (page: 17, entry: 11), now opens on "8. 2. 5."
  'vp-pct-1-3-2-5': (page: 17, entry: 6),
  // was (page: 17, entry: 17), now opens on "8. 2. 6."
  'vp-pct-1-3-2-6': (page: 17, entry: 12),
  // was (page: 18, entry: 5), now opens on "8. 2. 7."
  'vp-pct-1-3-2-7': (page: 18, entry: 0),
  // was (page: 18, entry: 11), now opens on "8. 2. 8."
  'vp-pct-1-3-2-8': (page: 18, entry: 6),
  // was (page: 18, entry: 17), now opens on "8. 2. 9."
  'vp-pct-1-3-2-9': (page: 18, entry: 12),
  // was (page: 19, entry: 5), now opens on "8. 2. 10."
  'vp-pct-1-3-2-10': (page: 19, entry: 0),
  // was (page: 20, entry: 6), now opens on "8. 3. 1."
  'vp-pct-1-3-3-1': (page: 20, entry: 1),
  // was (page: 20, entry: 12), now opens on "8. 3. 2."
  'vp-pct-1-3-3-2': (page: 20, entry: 7),
  // was (page: 20, entry: 18), now opens on "8. 3. 3."
  'vp-pct-1-3-3-3': (page: 20, entry: 13),
  // was (page: 21, entry: 5), now opens on "8. 3. 4."
  'vp-pct-1-3-3-4': (page: 21, entry: 0),
  // was (page: 21, entry: 11), now opens on "8. 3. 5."
  'vp-pct-1-3-3-5': (page: 21, entry: 6),
  // was (page: 21, entry: 17), now opens on "8. 3. 6."
  'vp-pct-1-3-3-6': (page: 21, entry: 12),
  // was (page: 22, entry: 5), now opens on "8. 3. 7."
  'vp-pct-1-3-3-7': (page: 22, entry: 0),
  // was (page: 22, entry: 11), now opens on "8. 3. 8."
  'vp-pct-1-3-3-8': (page: 22, entry: 6),
  // was (page: 22, entry: 17), now opens on "8. 3. 9."
  'vp-pct-1-3-3-9': (page: 22, entry: 12),
  // was (page: 23, entry: 5), now opens on "8. 3. 10."
  'vp-pct-1-3-3-10': (page: 23, entry: 0),
  // was (page: 24, entry: 6), now opens on "8. 4. 1."
  'vp-pct-1-3-4-1': (page: 24, entry: 1),
  // was (page: 24, entry: 12), now opens on "8. 4. 2."
  'vp-pct-1-3-4-2': (page: 24, entry: 7),
  // was (page: 24, entry: 18), now opens on "8. 4. 3."
  'vp-pct-1-3-4-3': (page: 24, entry: 13),
  // was (page: 25, entry: 5), now opens on "8. 4. 4."
  'vp-pct-1-3-4-4': (page: 25, entry: 0),
  // was (page: 25, entry: 11), now opens on "8. 4. 5."
  'vp-pct-1-3-4-5': (page: 25, entry: 6),
  // was (page: 25, entry: 17), now opens on "8. 4. 6."
  'vp-pct-1-3-4-6': (page: 25, entry: 12),
  // was (page: 27, entry: 2), now opens on "8. 4. 7."
  'vp-pct-1-3-4-7': (page: 26, entry: 0),
  // was (page: 27, entry: 8), now opens on "8. 4. 8."
  'vp-pct-1-3-4-8': (page: 27, entry: 3),
  // was (page: 27, entry: 14), now opens on "8. 4. 9."
  'vp-pct-1-3-4-9': (page: 27, entry: 9),
  // was (page: 28, entry: 5), now opens on "8. 4. 10."
  'vp-pct-1-3-4-10': (page: 28, entry: 0),
  // was (page: 29, entry: 6), now opens on "8. 5. 1."
  'vp-pct-1-3-5-1': (page: 29, entry: 1),
  // was (page: 29, entry: 12), now opens on "8. 5. 2."
  'vp-pct-1-3-5-2': (page: 29, entry: 7),
  // was (page: 29, entry: 18), now opens on "8. 5. 3."
  'vp-pct-1-3-5-3': (page: 29, entry: 13),
  // was (page: 30, entry: 5), now opens on "8. 5. 4."
  'vp-pct-1-3-5-4': (page: 30, entry: 0),
  // was (page: 30, entry: 11), now opens on "8. 5. 5."
  'vp-pct-1-3-5-5': (page: 30, entry: 6),
  // was (page: 30, entry: 17), now opens on "8. 5. 6."
  'vp-pct-1-3-5-6': (page: 30, entry: 12),
  // was (page: 31, entry: 5), now opens on "8. 5. 7."
  'vp-pct-1-3-5-7': (page: 31, entry: 0),
  // was (page: 31, entry: 11), now opens on "8. 5. 8."
  'vp-pct-1-3-5-8': (page: 31, entry: 6),
  // was (page: 31, entry: 17), now opens on "8. 5. 9."
  'vp-pct-1-3-5-9': (page: 31, entry: 12),
  // was (page: 32, entry: 5), now opens on "8. 5. 10."
  'vp-pct-1-3-5-10': (page: 32, entry: 0),
  // was (page: 33, entry: 6), now opens on "8. 6. 1."
  'vp-pct-1-3-6-1': (page: 33, entry: 1),
  // was (page: 33, entry: 12), now opens on "8. 6. 2."
  'vp-pct-1-3-6-2': (page: 33, entry: 7),
  // was (page: 34, entry: 5), now opens on "8. 6. 3."
  'vp-pct-1-3-6-3': (page: 34, entry: 0),
  // was (page: 34, entry: 11), now opens on "8. 6. 4."
  'vp-pct-1-3-6-4': (page: 34, entry: 6),
  // was (page: 35, entry: 6), now opens on "8. 6. 5."
  'vp-pct-1-3-6-5': (page: 35, entry: 0),
  // was (page: 36, entry: 4), now opens on "8. 6. 6."
  'vp-pct-1-3-6-6': (page: 35, entry: 7),
  // was (page: 37, entry: 7), now opens on "8. 6. 7."
  'vp-pct-1-3-6-7': (page: 36, entry: 5),
  // was (page: 37, entry: 14), now opens on "8. 6. 8."
  'vp-pct-1-3-6-8': (page: 37, entry: 8),
  // was (page: 38, entry: 6), now opens on "8. 6. 9."
  'vp-pct-1-3-6-9': (page: 38, entry: 0),
  // was (page: 38, entry: 13), now opens on "8. 6. 10."
  'vp-pct-1-3-6-10': (page: 38, entry: 7),
  // was (page: 39, entry: 6), now opens on "8. 7. 1."
  'vp-pct-1-3-7-1': (page: 39, entry: 1),
  // was (page: 39, entry: 12), now opens on "8. 7. 2."
  'vp-pct-1-3-7-2': (page: 39, entry: 7),
  // was (page: 39, entry: 19), now opens on "8. 7. 3."
  'vp-pct-1-3-7-3': (page: 39, entry: 13),
  // was (page: 40, entry: 5), now opens on "8. 7. 4."
  'vp-pct-1-3-7-4': (page: 40, entry: 0),
  // was (page: 40, entry: 11), now opens on "8. 7. 5."
  'vp-pct-1-3-7-5': (page: 40, entry: 6),
  // was (page: 40, entry: 18), now opens on "8. 7. 6."
  'vp-pct-1-3-7-6': (page: 40, entry: 12),
  // was (page: 41, entry: 6), now opens on "8. 7. 7."
  'vp-pct-1-3-7-7': (page: 41, entry: 0),
  // was (page: 41, entry: 12), now opens on "8. 7. 8."
  'vp-pct-1-3-7-8': (page: 41, entry: 7),
  // was (page: 42, entry: 10), now opens on "8. 7. 9."
  'vp-pct-1-3-7-9': (page: 41, entry: 13),
  // was (page: 43, entry: 5), now opens on "8. 7. 10."
  'vp-pct-1-3-7-10': (page: 43, entry: 0),
  // was (page: 43, entry: 11), now opens on "8. 7. 11."
  'vp-pct-1-3-7-11': (page: 43, entry: 6),
  // was (page: 43, entry: 17), now opens on "8. 7. 12."
  'vp-pct-1-3-7-12': (page: 43, entry: 12),
  // was (page: 44, entry: 5), now opens on "8. 7. 13."
  'vp-pct-1-3-7-13': (page: 44, entry: 0),
  // was (page: 44, entry: 11), now opens on "8. 7. 14."
  'vp-pct-1-3-7-14': (page: 44, entry: 6),
  // was (page: 45, entry: 7), now opens on "8. 7. 15."
  'vp-pct-1-3-7-15': (page: 44, entry: 12),
};
