import 'dart:convert';
import 'dart:io';

import 'package:wisdom_shared/wisdom_shared.dart';

import 'data/corpus_reader.dart';
import 'data/slicer_cache.dart';
import 'domain/document.dart';
import 'domain/site_page.dart';
import 'domain/theme_tokens.dart';
import 'manifest/build_manifest.dart';
import 'render/cache_headers.dart';
import 'render/landing_page.dart';
import 'render/page_template.dart';
import 'render/search_index.dart';
import 'render/site_assets.dart';
import 'render/stylesheet.dart';
import 'render/web_fonts.dart';

/// Version stamped into `<meta name="generator">` and `.manifest.json`.
/// Bump by hand; it is not a build id (§11.8 forbids anything that changes per
/// run).
const String generatorVersion = '0.1.0';

/// What a build produced.
class BuildReport {
  final int suttaPages;
  final int chapterPages;
  final int tocPages;
  final int contentFilesParsed;

  const BuildReport({
    required this.suttaPages,
    required this.chapterPages,
    required this.tocPages,
    required this.contentFilesParsed,
  });

  int get total => suttaPages + chapterPages + tocPages;
}

/// classify → slice → render → write.
///
/// The use case. Everything it calls is either a pure transform (`domain/`,
/// `render/`) or a reader (`data/`); this is the only place the two meet, and —
/// with `BuildManifest.writeTo` — the only place that writes.
class SiteGenerator {
  final CorpusReader reader;
  final TipitakaTree tree;
  final ThemeTokens tokens;

  /// Directory that receives `tipitaka/`, `assets/`, `fonts/`.
  final String outputDir;

  /// `static_site_generator/assets/` — the generator's *own* build inputs, as
  /// opposed to [CorpusReader.assetsPath], which is the app's.
  ///
  /// Both hold committed, hand-generated bytes the build only ever copies:
  /// `theme_tokens.json` and `emblem.png` here, the WOFF2 subsets there.
  final String packageAssetsPath;

  SiteGenerator({
    required this.reader,
    required this.tree,
    required this.tokens,
    required this.outputDir,
    required this.packageAssetsPath,
  });

  BuildReport generate(List<String> rootKeys) {
    _clearOutputDir();
    final cache = SlicerCache(reader: reader, tree: tree);

    // The grouping rule is **read, not run**. `foldedLeafKeys` is a frozen
    // `const` in `wisdom_shared` (`tool/plan_corpus.dart --write-snapshot`
    // writes it), so a re-sync of `assets/` can change what a page says and
    // never which pages exist — and a one-subtree build no longer measures the
    // whole corpus to find that out.
    final plan = SitePlan.build(
      tree: tree,
      rootKeys: rootKeys,
      foldedLeafKeys: foldedLeafKeys,
    );

    // Everything a page links is built or read before the first page, though
    // most of it is written after them: each URL carries a hash of its own
    // bytes (SiteAssets), so the bytes have to exist before a page can name
    // them.
    //
    // The search index is the reason this is worth spelling out — it used to be
    // built after the loop, and only the plan it needs was required to come
    // first. That is still true, and the plan is already here.
    final fonts = _readFonts();
    final css = buildStylesheet(
      tokens,
      fontVersion: fontsVersion([for (final font in fonts) font.bytes]),
    );
    final searchIndex = buildSearchIndex(plan: plan);
    final script = _readPackageAsset(
      siteScriptFileName,
      'the site will build without search or the ?layout= handler. Every page '
      'still works; the toolbar button stays hidden.',
    );
    final emblem = _readPackageAsset(
      emblemFileName,
      "the toolbar's home link will show a broken image on every page. Fix: "
      'run static_site_generator/assets/make_emblem.sh and commit its output.',
    );

    final assets = SiteAssets.forContent(
      css: css,
      // Decoded rather than passed as bytes: `site.js` is UTF-8 source, and
      // hashing the decoded string is hashing the same bytes back.
      script: script == null ? '' : utf8.decode(script),
      searchIndex: searchIndex,
      emblem: emblem ?? const <int>[],
    );

    final template = PageTemplate(
      tree: tree,
      generatorVersion: generatorVersion,
      assets: assets,
      urlFor: plan.urlFor,
    );
    final manifest = BuildManifest();

    var suttaPages = 0;
    var chapterPages = 0;
    var tocPages = 0;

    for (final page in plan.pages) {
      final sourceFileId = _sourceFileOf(page);
      if (sourceFileId == null) {
        // Cannot fire on the vendored corpus. Throws rather than warns because
        // skipping the page would leave a 404 that the site's own breadcrumbs,
        // TOCs and pagers still link to.
        throw StateError(
          'Page "${page.nodeKey}" (${page.kind.name}) has no content file. '
          'Its URL is already linked from its parent and siblings, so it '
          'cannot be skipped. Re-check assets/data/tree.json after a re-sync.',
        );
      }

      final slices = <String, NodeSlice>{};
      for (final sutta in page.suttas) {
        // A container's leaves can live in a different file than the container
        // itself (`FIGURES.containersWhoseLeavesSitElsewhere`), so each sutta
        // resolves its own.
        final fileId = sutta.contentFileId;
        if (fileId == null) {
          throw StateError(
            'Sutta "${sutta.nodeKey}" has no content file, so its text would '
            'be silently missing from "${page.nodeKey}".',
          );
        }
        slices[sutta.nodeKey] = cache.forFile(fileId).sliceFor(sutta.nodeKey);
      }

      // The container's own slice is its preamble; a leaf owns its rows
      // outright and has none. See [SitePage.hasPreamble].
      final preamble = page.hasPreamble
          ? cache.forFile(sourceFileId).sliceFor(page.nodeKey)
          : null;

      final html = template.render(
        page,
        slices: slices,
        preamble: preamble,
        previous: plan.previousOf(page),
        next: plan.nextOf(page),
        sourceFile: sourceFileId,
      );

      _write('$outputDir/${page.outputPath}', html);
      manifest.record(
        sourceFileId: sourceFileId,
        outputPath: page.outputPath,
        sourceHash: reader.contentFileHash(sourceFileId),
      );

      switch (page.kind) {
        case PageKind.sutta:
          suttaPages++;
        case PageKind.chapter:
          chapterPages++;
        case PageKind.toc:
          tocPages++;
      }
    }

    // The front door. Written on every build, one-subtree ones included: a
    // build whose origin 404s is a build nobody can click through.
    //
    // It lists the roots this build actually wrote, not `tree.roots`.
    // `--root all` has already resolved to all seven by the time it reaches
    // here (`bin/generate.dart`), so a whole-corpus `/` is unchanged; a subtree
    // `/` links only to pages that are in the upload, which is what lets
    // `deploy.sh` print the bare origin as the URL to smoke-test.
    _write(
      '$outputDir/${LandingPage.outputPath}',
      LandingPage(
        roots: [for (final key in rootKeys) tree[key]!],
        generatorVersion: generatorVersion,
        assets: assets,
        urlFor: plan.urlFor,
      ).render(),
    );

    _write('$outputDir/$stylesheetOutputPath', css);
    _write('$outputDir/$searchIndexOutputPath', searchIndex);
    // Root of the upload, not `assets/`: Cloudflare only reads it there. It is
    // static text, so it costs the build nothing and is written unconditionally
    // — a subtree preview caches exactly like production.
    _write('$outputDir/$cacheHeadersOutputPath', buildCacheHeaders());
    if (script != null) _writeBytes('$outputDir/$siteScriptOutputPath', script);
    if (emblem != null) _writeBytes('$outputDir/$emblemOutputPath', emblem);
    for (final font in fonts) {
      _writeBytes(
          '$outputDir/$fontsOutputDir/${font.face.relativePath}', font.bytes);
    }
    manifest.writeTo('$outputDir/.manifest.json',
        generatorVersion: generatorVersion);

    return BuildReport(
      suttaPages: suttaPages,
      chapterPages: chapterPages,
      tocPages: tocPages,
      contentFilesParsed: cache.parses,
    );
  }

  /// Empties the output directory before writing into it.
  ///
  /// The build only ever *adds* files, so without this a page that stops
  /// existing — a vagga crossing the grouping threshold after an upstream
  /// re-sync, a nodeKey that shifts — leaves its old HTML behind, and
  /// Cloudflare happily serves the orphan. §11.8's byte-determinism covers
  /// building the *same* input twice; it says nothing about building a changed
  /// one, which is exactly when stale files appear.
  ///
  /// A wipe rather than a reconcile against `.manifest.json`: the manifest
  /// lists pages, not `assets/` or `fonts/`, and a full rebuild takes 85 ms.
  ///
  /// **It will only wipe a directory it recognises as its own.** `outputDir`
  /// comes from `--out`, so a recursive delete here is one typo away from
  /// eating a directory that matters. An empty directory is fine to claim, and
  /// so is one holding a previous build (`.manifest.json` is the marker, which
  /// only this generator writes). Anything else stops the build.
  void _clearOutputDir() {
    final directory = Directory(outputDir);
    if (!directory.existsSync()) {
      directory.createSync(recursive: true);
      return;
    }

    // Probed directly rather than matched against `listSync()` paths: those are
    // joined with the platform separator, so a suffix test would silently never
    // fire on Windows and refuse every rebuild.
    final isPreviousBuild = File('$outputDir/.manifest.json').existsSync();
    if (directory.listSync().isNotEmpty && !isPreviousBuild) {
      throw StateError(
        '"$outputDir" is not empty and holds no .manifest.json, so it does not '
        'look like a directory this generator produced. Refusing to delete it. '
        'Point --out at a new or previously-generated directory.',
      );
    }

    directory.deleteSync(recursive: true);
    directory.createSync(recursive: true);
  }

  /// Which content file a page's text comes from.
  String? _sourceFileOf(SitePage page) =>
      page.node.contentFileId ??
      (page.suttas.isEmpty ? null : page.suttas.first.contentFileId);

  /// Reads one committed asset (the emblem, `site.js`) — null when it is not
  /// there.
  ///
  /// Same contract as the fonts: made by hand, committed, and the build only
  /// moves bytes (D9). **Read here rather than copied straight across** because
  /// the URL every page links carries a hash of these bytes (`SiteAssets`), so
  /// they have to be in hand before the first page is rendered, and written
  /// afterwards.
  ///
  /// A warning, not a throw, matching [_readFonts]: neither absence makes a
  /// page of scripture wrong, and [warning] says what the site loses.
  List<int>? _readPackageAsset(String fileName, String warning) {
    final source = File('$packageAssetsPath/$fileName');
    if (!source.existsSync()) {
      stderr.writeln('WARNING  ${source.path} missing — $warning');
      return null;
    }
    return source.readAsBytesSync();
  }

  /// Reads the committed WOFF2 subsets (D7).
  ///
  /// Fonts are a build **input**, like `theme_tokens.json`: `subset_fonts.sh`
  /// is run by hand and its output committed, so the build loop stays pure Dart
  /// with no Python in it. Here we only move bytes.
  ///
  /// Driven by [webFontFaces] — the same list the stylesheet writes its
  /// `@font-face` rules from — so the site ships exactly the faces it declares.
  /// Globbing `assets/fonts/` instead would also copy the Latin-only families
  /// the Flutter app bundles, which no CSS rule here names.
  ///
  /// Returns what it found rather than writing it, because the faces are hashed
  /// into the `@font-face` URLs before the stylesheet those rules live in is
  /// built — [_readPackageAsset] has the same shape for the same reason.
  List<({WebFontFace face, List<int> bytes})> _readFonts() {
    final source = Directory('${reader.assetsPath}/fonts');
    if (!source.existsSync()) {
      stderr.writeln('WARNING  ${source.path} missing — no fonts copied.');
      return const [];
    }

    final found = <({WebFontFace face, List<int> bytes})>[];
    final missing = <String>[];
    for (final face in webFontFaces(tokens)) {
      final file = File('${source.path}/${face.relativePath}');
      if (!file.existsSync()) {
        missing.add(face.relativePath);
        continue;
      }
      found.add((face: face, bytes: file.readAsBytesSync()));
    }

    if (missing.isEmpty) return found;
    stderr.writeln(
      'WARNING  ${missing.length} of the declared WOFF2 faces are not in '
      '${source.path} (${missing.first}${missing.length > 1 ? ', …' : ''}). '
      'Those pages fall back to a system Sinhala face, which is NOT the face '
      'the conjuncts were verified against. Fix: run '
      'assets/fonts/subset_fonts.sh and commit its *-Subset.woff2 output '
      '(needs `pip install "fonttools[woff]"`).',
    );
    return found;
  }

  void _write(String path, String contents) {
    final file = File(path);
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(contents);
  }

  void _writeBytes(String path, List<int> bytes) {
    final file = File(path);
    file.parent.createSync(recursive: true);
    file.writeAsBytesSync(bytes);
  }
}
